apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: d2c-api
  labels:
    app: d2c-api
spec:
  selector:
    matchLabels:
      monitoring: d2c-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: d2c-outbox-publisher
  labels:
    app: d2c-outbox-publisher
spec:
  selector:
    matchLabels:
      monitoring: d2c-outbox
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: d2c-event-consumer
  labels:
    app: d2c-event-consumer
spec:
  selector:
    matchLabels:
      monitoring: d2c-consumer
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
